[workspace]
resolver = "3"
members = [
    "server",
    "client-lib",
    "ui"
]

[workspace.dependencies]
anyhow = "1.0"
tokio = { version = "1.0", features = ["full"] }
uuid = { version = "1.7.0", features = ["v4"] }
